CREATE TABLE roles(
    roleId CHAR(36) NOT NULL,
    roleType VARCHAR(64) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_role_id PRIMARY KEY (roleId),
    CONSTRAINT UK_role_type UNIQUE KEY (roleType)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;