CREATE TABLE user_roles(
    roleId CHAR(36) NOT NULL,
    userId CHAR(36) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_user_roles_id PRIMARY KEY (roleId,userId),
    CONSTRAINT FK_user_roles_users FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE,
    CONSTRAINT FK_user_roles_roles FOREIGN KEY (roleId) REFERENCES roles(roleId) ON DELETE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;